#!/bin/bash

# Jan 2020
# tderrien@univ-rennes1.fr
# Goal : QC of nanopore runs
#	- compare runs with NanoPack/NanoComp : https://github.com/wdecoster/nanocomp
#	- check individual run with minionQC
##################################################################################################################

# INSTALL
####################
# note pip3 for python3
#pip3 install NanoComp

# And install NanoPack
#pip3 install nanopack

# add it to .profile 
#export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.7/bin/
###################################################################################################################


# RUN 
######################
# List summary files
LIST=$(for f in $(find /Volumes/Chiens/NanoporeDATA/ -name "*sequencing_summary.txt");do echo $f;done | transp.awk)

# or update with input file summary with n cols : *** all_summary.txt ***
# input  species name    color   path_summary
LISTFILE=$(awk '$1!~/^#/{print $NF}'          all_summary.txt | transp.awk)
LISTNAME=$(awk '$1!~/^#/{print $1"-"$2"-"$3}' all_summary.txt | transp.awk)
LISTCOL=$( awk '$1!~/^#/{print $4}'           all_summary.txt | transp.awk)
NBRUN=$(awk '{print NR-1}' all_summary.txt  | tail -1)

# Run NanoComp 	: real	20m6.888s
# colors 	: https://matplotlib.org/3.1.0/gallery/color/named_colors.html
DATECUR=$(date +%F)
OUTDIR=./compare-runs-${NBRUN}-${DATECUR}
time NanoComp -t 10 --summary $LISTFILE --colors $LISTCOL --outdir $OUTDIR --names $LISTNAME

# copy on genouest for putonWeb
DIR_GENO="/home/genouest/umr6061/recomgen/tderrien/nano_report/"
scp $OUTDIR/NanoComp-report.html tderrien@genossh.genouest.org:$DIR_GENO/NanoComp-report-${DATECUR}.html

# Nanoplot for bam file was launched on genoculster
# /groups/dog/data/canFam3/NGS/Melanoma/DNA/WGS/MINION/RESULTS/nanoplot/README
BAM=/groups/dog/data/canFam3/NGS/Melanoma/DNA/WGS/MINION/twinyLignee.sorted.bam
OUTDIR="./bam_nanoplots"

NanoPlot --threads 8  --bam $BAM  -o $OUTDIR
